### ISSUE TITLE
Misspelling "sigle"

### ISSUE THREAD

**Issue by zdenekhejl** [MarekProkop/search-analytics-test#3]
**Source:** "Only the **SIGLE** dimension page and the combination of dimensions page and date fall into this group. "

**Correction:** "Only the **SINGLE** dimension page and the combination of dimensions page and date fall into this group. "

**Comment by MarekProkop** [comment]
Moc děkuju, Zdeňku.

**Comment by zdenekhejl** [comment]
Rádo se stalo.
